feat: hospital API の実装
unicorn-hal/unicorn-monorepo pull request #12
Opened 2024-10-17 09:57 UTC by MasayaIkeno

## 概要
hospital API の実装

## 変更点
"/hospitals"と、"/hospitals/{hospitalID}"を実装

- ドメイン、コントローラ、リポジトリ、クエリサービスを実装
- テストコードの記述

## 確認したこと
- テストにて、Swagger の要件に合うことを確認。

2024-10-17 09:58 UTC, MasayaIkeno commented
@naruto1031 
レビューお願いします！

2024-10-17 10:23 UTC, naruto1031 requested changes
@MasayaIkeno 
とりあえずコメントしました！！あとでペアプロしましょう！

2024-10-17 10:23 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/controller/hospital/HospitalController.kt
> +            ResponseEntity.status(500).build()
[good]
しっかりX-UIDを設定できていて素晴らし！！助かります

2024-10-17 10:23 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/controller/hospital/HospitalController.kt
> +        return try {
[nits]
```suggestion
    fun getHospitalById(@RequestHeader("X-UID") uid: String, @PathVariable hospitalID:UUID): ResponseEntity<HospitalDto> {
        return try {
```

ここUUIDで行けると思います！

2024-10-17 10:23 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/hospital/Hospital.kt
> +)
[imo]
今回Getのみの実装なので、Domain Modelは定義しなくても良いかも？？
後続で実装する分には賛成です！(諸々追加しそうな関数とかありそうだし)

2024-10-17 10:23 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/query_service/hospital/HospitalQueryService.kt
> +
[must]
Swaggerの定義だと`data`がプロパティ名です！
```suggestion
data class HospitalResult(
    val data: List<HospitalDto>
)

```

2024-10-17 10:23 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/hospital/HospitalGetByIdTest.kt
> +
@MasayaIkeno 
[ask]
ここ、getbyの実装をmockした意図はありますか？

例えば、今回の実装だと「Controller」の実装テストはできていても、「QueryService」の実態に対するテストができていないように思えます！(Controllerの単体テストになっている？)

このテスト実装にするのであれば、QuerySeriveのテストを書く必要がありそうな気がします！

2024-10-17 10:23 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/hospital/HospitalGetByIdTest.kt
> +    fun `should return 500 when an internal server error occurs for getHospitalById`() {
[good]
notfoundとinternal server errorのテストケースが書けているはとても良きです！！

2024-10-17 10:23 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/hospital/HospitalGetByIdTest.kt
> +
QueryServieとControllerの単体テストを実施し、別途統合テストを行うという思想であれば賛成です！！

2024-10-17 10:23 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/query_service/hospital/HospitalQueryService.kt
> +        val hospital_uuid = UUID.fromString(hospitalID)
[nits]
PathParamでUUIDを定義すれば、ここが要らなくなる

2024-10-17 10:23 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/hospital/HospitalGetTest.kt
> +        val result = mockMvc.perform(MockMvcRequestBuilders.get("/hospitals").headers(HttpHeaders().apply {
上記コメと同様です！

2024-10-17 11:11 UTC, MasayaIkeno commented on api-server/src/main/kotlin/com/unicorn/api/domain/hospital/Hospital.kt
> +)
了解です
一旦このまま残しておきます！

2024-10-17 11:12 UTC, MasayaIkeno commented on api-server/src/main/kotlin/com/unicorn/api/query_service/hospital/HospitalQueryService.kt
> +
すいません修正します！

2024-10-18 14:45 UTC, MasayaIkeno commented
@naruto1031 
修正しました。
レビューお願いします！

2024-10-18 14:47 UTC, naruto1031 commented
@MasayaIkeno 
FileChangeが膨大になってしまっているので、リリースブランチに対してmainの変更分を取り込んでください！

2024-10-18 15:29 UTC, naruto1031 approved these changes
@MasayaIkeno 
![LGTM](https://img.shields.io/badge/review-LGTM-green)
よいです！！firstOrNullのコメントはめっちゃ細かいとこなので対応はおまかせします！

2024-10-18 15:29 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/query_service/hospital/HospitalQueryService.kt
> +        }.firstOrNull()
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
基本的にデータベースとしてUUIDを採用しているためレコードの一意性が保たれています。そのためコードベースでも、返却するレコードが必ず一件だけであることを保証する`singleOrNull()`のほうがよいです！細かいですが...
```suggestion
        }.singleOrNull()
```

2024-10-18 15:29 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/hospital/HospitalGetByIdTest.kt
> +        }))
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
UUIDがinvalidのときのテスト書かれているの良きです

2024-10-18 15:29 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/query_service/hospital/HospitalQueryService.kt
> +        }.firstOrNull()
データベースに不整合が発生した際、複数件該当するレコードが出て来てしまうことがあるかもしれません。そのときにSingleOrNull()にすると二件以上の場合はnullになります

2024-10-18 17:01 UTC, merged