[TSK-267] emergencyAPIのdomainとrepository実装
unicorn-hal/unicorn-monorepo pull request #123
Opened 2024-11-29 07:54 UTC by SadaHiroki

## 概要
emergencyAPIのdomainとrepository実装

## 変更点
- domainの追加
- repositoryの追加
- それぞれのテスト追加
- Insert分のsqlファイル追加

## 確認したこと
- テストが通ったこと

## リリース時に確認すること
- リリース作業時に確認することを記載してください。

2024-11-29 08:07 UTC, naruto1031 requested changes
@SadaHiroki 
コメントしました！

2024-11-29 08:07 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/infrastructure/emergency/EmergencyRepository.kt
> +class EmergencyRepositoryImpl(
![must-badge](https://img.shields.io/badge/review-must-red.svg)
このRepositoryはキューとしての運用だったと思うのですが、deleted_atがnullである、一番最後のレコードを取得する関数と、そのレコード削除を行う関数が実装抜けしている気がします。

2024-11-29 08:23 UTC, SadaHiroki commented on api-server/src/main/kotlin/com/unicorn/api/infrastructure/emergency/EmergencyRepository.kt
> +class EmergencyRepositoryImpl(
@naruto1031 
修正しました
再レビューお願いします
https://github.com/unicorn-hal/unicorn-monorepo/pull/123/commits/a2b290dae85582f4c71f66dcb2bb3d0eb86b80e3

2024-11-29 08:28 UTC, SadaHiroki commented on api-server/src/main/kotlin/com/unicorn/api/infrastructure/emergency/EmergencyRepository.kt
> +class EmergencyRepositoryImpl(
これLIMIT 1いらないか？

2024-11-30 07:44 UTC, naruto1031 reviewed
@SadaHiroki
コメントしました！

2024-11-30 07:44 UTC, naruto1031 commented on api-server/src/test/resources/db/emergency/Insert_Emergency_Data.sql
> +        null
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
上記テストケースだと、どれが一番古いデータかというのがわかりづらいです！10分置きなど、少し時間をずらしたtimestampにしましょう！

2024-11-30 07:44 UTC, naruto1031 commented on api-server/src/test/resources/db/emergency/Insert_Emergency_Data.sql
> +        1.1,
どちらのテストケースも座標が同じなので、どちらが取得できたかがわからない気がします！

2024-11-30 08:23 UTC, SadaHiroki commented on api-server/src/test/resources/db/emergency/Insert_Emergency_Data.sql
> +        null
@naruto1031 
修正しました。
再レビューお願いします！
https://github.com/unicorn-hal/unicorn-monorepo/pull/123/commits/d0101b5f6aa361e2c7a9442c552e8caa56f66a04

2024-12-01 03:18 UTC, naruto1031 approved these changes

2024-12-01 03:19 UTC, merged