[TSK-189] medicine API おくすり一覧取得機能の実装
unicorn-hal/unicorn-monorepo pull request #34
Opened 2024-10-24 06:04 UTC by MasayaIkeno

## 概要
おくすり一覧取得機能の実装

## 変更点

- /medicine にコントローラ層とクエリサービス層を実装。
- コントローラの単体テストを記述。

## 確認したこと
- テストが通ること。

2024-10-24 06:05 UTC, MasayaIkeno commented
@naruto1031 
レビューお願いします。

2024-10-25 07:33 UTC, naruto1031 requested changes
コメントしましたー細かい修正ですが、よろしくお願いします！

2024-10-25 07:33 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/controller/medicine/MedicineController.kt
> +                ResponseEntity.status(400).body("User not found")
[super-nits]
ここは自分が用意したRequestErrorを用いると erroTypeプロパティにmessageを入れることができるので、もしよければ！！！
```suggestion
                ResponseEntity.status(400).body(ResponseError("User not found"))
```

2024-10-25 07:33 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/query_service/medicine/MedicineQueryService.kt
> +        val sql = """
![next-badge](https://img.shields.io/badge/review-next-blueviolet)
// language=posgresqlを入れてくれるとハッピーです

2024-10-25 07:33 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicinesGetTest.kt
> +
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
uidが不正値だった場合のテストケースも欲しいです！

2024-10-25 07:33 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/controller/medicine/MedicineController.kt
> +            } else {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
ここは例外ケースなので、早期リターンのほうがきれいです！
```suggestion
            val user = userQueryService.getOrNullBy(uid)
            
            if(user == null) {
               return ResponseEntity.status(400).body("User not found")
            }
            
             val result = medicineQueryService.getMedicines(uid)
```

2024-10-25 09:43 UTC, naruto1031 approved these changes

2024-10-25 09:44 UTC, merged