[TSK-212] primaryDoctor の ドメイン層とリポジトリ層の実装
unicorn-hal/unicorn-monorepo pull request #56
Opened 2024-10-29 16:26 UTC by MasayaIkeno

## 概要
primary doctor API のドメイン層とリポジトリ層の実装

## 変更点
- PrimaryDoctor.kt と PrimaryDoctorRepository.kt の追加。
- 対応するテストの記述。
- テスト用SQLファイルの追加。

## 確認したこと
- テストが通ること。

2024-10-30 04:00 UTC, naruto1031 requested changes
@MasayaIkeno 
コメントしました！コメントの部分は対応お願いします！

2024-10-30 04:06 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
> +) {
ああ、でも1のパターンだと、更新で困るのか...

2024-10-30 04:08 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
> +) {
こんな感じで運用してみたらどうだろう？

```
data class PrimaryDoctors(
  val userID: UserID,
  val doctors: List<PrimaryDoctor>
)

data class PrimaryDoctor(
   val primaryDoctorID: PrimaryDoctorID,
   val doctorID: DoctorID
)
```

2024-10-30 04:11 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
> +) {
これを踏まえると、実はUserに紐づける方が簡単だったり？

2024-10-30 04:11 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
> +) {
@MasayaIkeno 
意見を聞きたいです！

2024-10-30 05:39 UTC, MasayaIkeno commented
@naruto1031 
修正したので再レビューお願いします

2024-10-30 12:24 UTC, naruto1031 requested changes
@MasayaIkeno 
再レビューしました〜
むずかしい内容ですみません...時間は全然かけて良いので、対応お願いします！！

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepository.kt
> +        """.trimIndent()
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
これ例えば、かかりつけ医がA, Bさんから、C, Bさんに変わった場合、正常にAさんはかかりつけ医から除外されますか？

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctorTest.kt
> +    fun `update doctors list`() {
かかりつけ医が変更になった場合のテストもお願いします！

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepositoryTest.kt
> +    fun `should store multiple primary doctors`() {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
複数ユーザのテストができているのはとても良きです！

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
> +    val doctors: List<PrimaryDoctor>
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
userをID参照する実装

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepository.kt
> +class PrimaryDoctorRepositoryImpl(
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
これ細かいようですが、PrimaryDoctorsを永続化するRepositoryとして運用した方が良いと思います！
```suggestion
interface PrimaryDoctorsRepository {
    fun store(primaryDoctors: PrimaryDoctors): PrimaryDoctors
    fun getOrNullBy(primaryDoctorID: PrimaryDoctorID): PrimaryDoctors
}

@Repository
class PrimaryDoctorsRepositoryImpl(
```

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepository.kt
> +class PrimaryDoctorRepositoryImpl(
保存と取得のデータ型がバラバラになっている

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
> +    }
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
fromStoreはファクトリメソッドなので、companion object内に定義すべきだと思います！

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
> +    }
createメソッドとの実装に若干乖離があるのも違和感ありです！！

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
> +data class PrimaryDoctor(
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
PrimaryDoctorにもfromStore・createメソッドを生やしてもよいかも
対応はお任せします！

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
> +data class PrimaryDoctor(
上記実装にするのであれば、private constructorにしていただけるとありがたいです！

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepositoryTest.kt
> +        primaryDoctorRepository.store(primaryDoctors)
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
単体テストにおいて、craeteとupdateの双方のメソッドをテストするのは、テストがリファクタリングに弱くなるので推奨できません！登録されている既存のデータにupdateをするようにしましょう！

2024-10-30 12:24 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepository.kt
> +        return primaryDoctors.doctors.map { primaryDoctor ->
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
ここら辺の登録処理はとても良いと思います！

2024-11-02 02:19 UTC, MasayaIkeno commented
@naruto1031  
レビューお願いします

2024-11-03 02:14 UTC, naruto1031 requested changes
@MasayaIkeno 
コメントしました〜
どこかのタイミングでペアプロしましょう！！

2024-11-03 02:14 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepository.kt
> +        }
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
ここは一旦Userに紐づく、primaryDoctorを論理削除してしまっても良いと思います！
```suggestion
            val deleteSql = """
        UPDATE primary_doctors
        SET deleted_at = CURRENT_TIMESTAMP
        WHERE user_id = :userId  AND deleted_at IS NULL
    """.trimIndent()

            val deleteParams = MapSqlParameterSource()
                .addValue("userId", primaryDoctors.userID.value)
            namedParameterJdbcTemplate.update(deleteSql, deleteParams)
```

2024-11-03 02:14 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepository.kt
> +        """.trimIndent()
ここでPrimaryDoctorsをループしてupsertする
```suggestion
       primaryDoctors.doctors.forEach { primaryDoctor ->
            // language=postgresql
            val insertSql = """
        INSERT INTO primary_doctors (
            primary_doctor_id,
            doctor_id,
            user_id,
            created_at,
            deleted_at
        ) VALUES (
            :primaryDoctorId,
            :doctorId,
            :userId,
            CURRENT_TIMESTAMP,
            NULL
        ) ON CONFLICT (primary_doctor_id) DO 
        ...
        """.trimIndent()
```

2024-11-04 08:22 UTC, MasayaIkeno commented
@naruto1031 
レビューお願いします

2024-11-04 12:05 UTC, naruto1031 approved these changes
![LGTM](https://img.shields.io/badge/review-LGTM-green)
OKです〜

2024-11-05 13:52 UTC, merged