[TSK-169] health_checkupの一括取得実装
unicorn-hal/unicorn-monorepo pull request #63
Opened 2024-11-03 04:02 UTC by SadaHiroki

## 概要
- 検査情報を一覧取得するAPIを実装する
- 検査情報が適切に取得できているかどうかを確認するテストを行う

## 変更点
- Controllerに/health_checkupsのGETを追加
- 一括取得のテストを行うためのテストファイルを追加

## 確認したこと
- テストが通ることを確認
- ローカル環境で一括取得ができたことを確認

## リリース時に確認すること
- リリース作業時に確認することを記載してください。

2024-11-03 09:15 UTC, naruto1031 requested changes
すみません一点だけ対応お願いします！

2024-11-03 09:15 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupController.kt
> +    @GetMapping("/health_checkups")
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
この実装も、users/{userID}にしていただけると助かります！

2024-11-03 23:54 UTC, SadaHiroki commented on api-server/src/main/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupController.kt
> +    @GetMapping("/health_checkups")
@naruto1031 
修正しました
再レビューよろしくお願いします
https://github.com/unicorn-hal/unicorn-monorepo/pull/63/commits/f19094b0279faba165d363248d83f6db809ba1b3

2024-11-04 07:20 UTC, naruto1031 approved these changes
![LGTM](https://img.shields.io/badge/review-LGTM-green)
ありがとうございます〜

2024-11-04 07:21 UTC, merged