[TSK-193] chronic_diseaseの持病一覧取得の実装
unicorn-hal/unicorn-monorepo pull request #81
Opened 2024-11-06 07:02 UTC by SadaHiroki

## 概要
- 持病情報を一括取得するAPIを実装する
- 持病情報が適切に取得できているかどうかを確認するテストを行う

## 変更点
- ControllerにGetを追加
- QueryServiceを追加
- GETのテストを行うテストファイルを追加

## 確認したこと
- テストが通ることを確認
- ローカル環境で一覧取得できたことを確認

## リリース時に確認すること
- リリース作業時に確認することを記載してください。

2024-11-06 07:04 UTC, SadaHiroki commented on api-server/src/main/kotlin/com/unicorn/api/query_service/chronic_disease/ChronicDiseaseQueryService.kt
> +            """.trimIndent()
一応テストは通ったのですが、SQLがこれで良いのか不安なので一番見てほしいです

2024-11-07 14:03 UTC, naruto1031 requested changes
コメントしました〜SQLの対応だけお願いします！

2024-11-07 14:03 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/query_service/chronic_disease/ChronicDiseaseQueryService.kt
> +            """.trimIndent()
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
実装自体は問題なさそうです！
table1, table2という表記方法は変えたほうが良いと思います。
```suggestion
            """
              SELECT
                  cd.chronic_disease_id,
                  d.disease_name
              FROM
                  chronic_diseases AS cd
              INNER JOIN
                  diseases AS d
              ON
                  cd.disease_id = d.disease_id
              WHERE
                  cd.user_id = :userID
              AND
                  cd.deleted_at IS NULL

            """.trimIndent()
```

2024-11-07 14:03 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/chronic_disease/ChronicDiseaseGetTest.kt
> +    fun `return 200 when get chronic_disease`() {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
持病が二件以上ある場合のテストもあると尚良だと思います！(追加任意)

2024-11-08 04:09 UTC, SadaHiroki commented on api-server/src/main/kotlin/com/unicorn/api/query_service/chronic_disease/ChronicDiseaseQueryService.kt
> +            """.trimIndent()
@naruto1031 
修正しました
再レビューおねがいします
https://github.com/unicorn-hal/unicorn-monorepo/pull/81/commits/bfdf57bdd39745395d06a86c45ee195954e21cf1

2024-11-08 07:02 UTC, naruto1031 approved these changes
OKです〜

2024-11-08 07:20 UTC, merged