[TSK-229] doctorのUUID重複チェック
unicorn-hal/unicorn-monorepo pull request #84
Opened 2024-11-08 08:47 UTC by SadaHiroki

## 概要
doctorのPOSTで使うdepartmentIDの重複チェック

## 変更点
- Applicationにチェックを追加
- テスト追加

## 確認したこと
- テストが通ったことを確認

## リリース時に確認すること
- リリース作業時に確認することを記載してください。

2024-11-08 08:51 UTC, naruto1031 requested changes
コメントしました！

2024-11-08 08:51 UTC, naruto1031 requested changes

2024-11-08 08:51 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/application_service/doctor/SaveDoctorService.kt
> +
![must-badge](https://img.shields.io/badge/review-must-red.svg)
このDepartmentID関連の処理は、DoctorのCreate処理内で記述できます！

2024-11-08 08:52 UTC, SadaHiroki commented on api-server/src/main/kotlin/com/unicorn/api/application_service/doctor/SaveDoctorService.kt
> +
ユルサナイ

2024-11-09 00:53 UTC, SadaHiroki commented on api-server/src/main/kotlin/com/unicorn/api/application_service/doctor/SaveDoctorService.kt
> +
@naruto1031 
修正しました
再レビューお願いします
https://github.com/unicorn-hal/unicorn-monorepo/pull/84/commits/4dba70f455ca656cf8df2b8188bd6e8888e584a5

2024-11-09 00:55 UTC, naruto1031 approved these changes
OKです！

2024-11-09 00:55 UTC, merged