[TSK-227] healthCheckupの検査結果メール送信
unicorn-hal/unicorn-monorepo pull request #92
Opened 2024-11-11 04:29 UTC by SadaHiroki

## 概要
healthCheckupが登録された際に検査結果をかかりつけ医に一斉メール送信をする機能

## 変更点
- JavaMail追加
- application.propertiesの環境変数追加
- README変更
- Circleciのenv追加
- Serviceの追加
- Controllerの追加
- Domainの追加
- メール送信のテストを行うファイルの追加

## 確認したこと
- テストが通ったこと(テスト時にはメールの送信はされない)
- ローカル環境でメール送信ができたこと(メールタイトル及びボディは、相談の上変更予定)
![スクリーンショット (3)](https://github.com/user-attachments/assets/31b1293c-68b7-4161-a01b-1595f3e5067d)

## リリース時に確認すること
- リリース作業時に確認することを記載してください。

2024-11-11 04:37 UTC, SadaHiroki commented
ローカル環境（postman）でPOST送信した時、メール送信の処理を挟むため登録結果のレスポンスが返ってくるのが遅い。
５秒ぐらいかかる

2024-11-11 04:58 UTC, naruto1031 requested changes
@SadaHiroki 
諸々コメントしました！

2024-11-11 04:58 UTC, naruto1031 commented on README.md
> +MAIL_PASSWORD=379f0847787733
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
ここ怖いのですが、このPWとUserNameは公開して良いものですか？

2024-11-11 04:58 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SendMailHealthCheckupService.kt
> +                <p>${healthCheckup.medicalRecord}</p>
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
検査結果は情報量が多くなる可能性があるので、メール内に記述しなくても良いと思います！

2024-11-11 04:58 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SendMailHealthCheckupService.kt
> +                <botton><a href="#">検査結果を確認する</a></button>
![must-badge](https://img.shields.io/badge/review-must-red.svg)
HTMLの規約上、button内にインタラクティブ要素を入れるのは、W3Cの規約違反であり、一部ブラウザで誤動作を起こしかねないので、aタグ用いるのであればaタグをbuttonのようなスタイルにするなどの対応が必要です。

```suggestion
                <a href="#">検査結果を確認する</a>
```

2024-11-11 04:58 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SendMailHealthCheckupService.kt
> +                <botton><a href="#">検査結果を確認する</a></button>
https://qiita.com/khsk/items/c026b4a21ac27b2cea71

2024-11-11 04:58 UTC, naruto1031 commented on .circleci/config.yml
> +        MAIL_PORT: 2525
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
CI実行時にメールが送信される想定ですか？

2024-11-11 04:58 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupSendMailTest.kt
> +package com.unicorn.api.controller.health_checkup
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
HealthCheckupのPOST TEST実行時に、メールは送信されますか？

2024-11-11 04:58 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupSendMailTest.kt
> +package com.unicorn.api.controller.health_checkup
POST、TESTの方に追記するでも良いと思い質問しました

2024-11-11 04:58 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupSendMailTest.kt
> +    }
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
このテストだと、単純にPOSTのTESTと同義な実装をしてしまっているように感じます。
`doNothing().`when`(mailTransport).send(anyString(), anyString(), anyString())`
上記が呼ばれたかどうかのテストが必要かなと感じました。
このテストを作成した意図があれば教えてください！！

2024-11-11 04:58 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/domain/health_checkup/HealthCheckupMailEvent.kt
> +data class HealthCheckupMailEvent(
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
このようなドメインイベントの命名に関しては、`何を持ってこのイベントが発火したのか`が言えると良いと思います。

例えば今回で言うと、検査情報が保存されたことにトリガーするので、`HealthCheckupSavedEvent`のような命名になると思います！

2024-11-11 05:01 UTC, SadaHiroki commented on README.md
> +MAIL_PASSWORD=379f0847787733
username passwordはMailtrapのものになります

2024-11-11 05:03 UTC, SadaHiroki commented on .circleci/config.yml
> +        MAIL_PORT: 2525
実行時には送信されない想定ですが、記述しないとcircleのテストが落ちてしまいます

2024-11-11 05:03 UTC, naruto1031 commented
> ローカル環境（postman）でPOST送信した時、メール送信の処理を挟むため登録結果のレスポンスが返ってくるのが遅い。 ５秒ぐらいかかる

ここら辺参考になるかも
https://qiita.com/alpha_pz/items/0d709fa0e86b81ef0bb7

2024-11-11 05:04 UTC, SadaHiroki commented on api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupSendMailTest.kt
> +package com.unicorn.api.controller.health_checkup
postテストの時にも送信されません

2024-11-11 05:05 UTC, SadaHiroki commented on api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupSendMailTest.kt
> +    }
メールのControllerとServiceを新規で作成したので、テストも新規で必要だと思い作成しました

2024-11-11 05:44 UTC, SadaHiroki commented on api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SendMailHealthCheckupService.kt
> +                <botton><a href="#">検査結果を確認する</a></button>
@naruto1031 
mustは修正しました
https://github.com/unicorn-hal/unicorn-monorepo/pull/92/commits/7ae5d0625c626cdadec991e13fe89acbc9683455

2024-11-11 06:13 UTC, SadaHiroki commented
> > ローカル環境（postman）でPOST送信した時、メール送信の処理を挟むため登録結果のレスポンスが返ってくるのが遅い。 ５秒ぐらいかかる
> 
> ここら辺参考になるかも https://qiita.com/alpha_pz/items/0d709fa0e86b81ef0bb7

非同期処理できた
https://github.com/unicorn-hal/unicorn-monorepo/pull/92/commits/0745e193b028289756c0d19aec42dfd96e6c2ef4

2024-11-11 06:35 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SendMailHealthCheckupService.kt
> +                <a href="#">検査結果を確認する</a>
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

```html
<h1>${user.firstName} ${user.lastName}の検査結果</h1>
<p>患者様の検査結果をお知らせします。</p>
```
上記文言はあっても良いかなと思いました

2024-11-11 06:35 UTC, naruto1031 commented on README.md
> +MAIL_PASSWORD=379f0847787733
@SadaHiroki 
一旦READMEに記述するのではなく、Notionでの公開にとどめてください！！

2024-11-11 06:35 UTC, naruto1031 commented on .circleci/config.yml
> +        MAIL_PORT: 2525
@SadaHiroki 
Circle CIへのプロジェクト招待メールを送ったので、そこから環境変数経由で設定するように変更してください。

https://qiita.com/chisato-ygc/items/6662e9ced6a6ee3b2fe9#%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%81%A7%E3%81%AE%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0

2024-11-11 06:42 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupSendMailTest.kt
> +    }
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
MailのControllerはイベントハンドラなので、直接ではなく間接的に呼び出されます。よって単純にAPIテストを記述するとPOST周りのテストと重複してしまうというわけです。

もしイベントハンドラ周りのテストを書くのであれば、イベントハンドラを直接呼び出すような結合テストを記述しましょう！

個人的に、今回はそこまでのテストは必要ないとおもいます

2024-11-11 06:44 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SendMailHealthCheckupService.kt
> +                <p>${healthCheckup.medicalRecord}</p>
@SadaHiroki 
表現が悪かったですね。。medical recordのことです

2024-11-11 06:46 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupSendMailTest.kt
> +    }
上記でお伝えしたように、JUnitでは、特定のメソッドが呼び出されたかどうかを判定することができるので、そちらを用いてmailTrapを呼び出したかどうかのテストをすると良いと思います

2024-11-11 07:21 UTC, SadaHiroki commented on api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SendMailHealthCheckupService.kt
> +                <a href="#">検査結果を確認する</a>
@naruto1031 
レビューの内容すべて修正しました！
再レビューお願いします！

2024-11-12 04:19 UTC, SadaHiroki commented
https://github.com/user-attachments/assets/90ab4937-bb47-47b3-9fd9-d67df603eae6

@naruto1031 
ローカル環境でのメール送信処理の動作確認動画です

2024-11-13 04:14 UTC, SadaHiroki commented
@naruto1031 
すべてのレビュー内容、実際にメール送信を行いました。
再レビューよろしくお願いいたします。

2024-11-13 06:09 UTC, naruto1031 approved these changes
![LGTM](https://img.shields.io/badge/review-LGTM-green)
基本的にはOKですQuerySerivceの部分はできるだけReposiotryに変えてくれると助かります！

2024-11-13 06:09 UTC, naruto1031 commented on api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SendMailHealthCheckupService.kt
> +        val user =
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
ここはApplication Serviceなので、できればQuerySerivceではなくRepositoryを呼び出すようにしてください！！

2024-11-13 08:07 UTC, merged