[TSK-213] Domain,Repositoryの実装
unicorn-hal/unicorn-monorepo pull request #94
Opened 2024-11-14 14:57 UTC by lenny817

## 概要
- 予約情報のdomainとrepositoryの実装
- 予約情報のdomainとrepositoryが動作しているかどうかを確認するテストの実装

## 変更点
- domain/call/Call.ktの追加
- infrastructure/call/CallRepository.ktの追加
- マイグレーションファイル(V032__Refactor_CallReservations_Table.sql)の追加
- それぞれのテストを行うテストファイルを追加

## 確認したこと
- テストが全て通ること

2024-11-15 06:00 UTC, naruto1031 requested changes
コメントしました！

2024-11-15 07:01 UTC, MasayaIkeno reviewed
@lenny817 @naruto1031 
コメントしました！

2024-11-15 07:01 UTC, MasayaIkeno commented on api-server/src/main/resources/db/migration/V032__Refactor_CallReservations_Table.sql
TIME ZONE を追加した理由って何かありますか？

2024-11-15 07:52 UTC, naruto1031 commented on api-server/src/main/resources/db/migration/V032__Refactor_CallReservations_Table.sql
@MasayaIkeno 
データベースに対して、正確にUTCで保存するためです！！

Time Zoneがないと、ユーザーがUTCで保存したのか、JSTで保存したのかが不明瞭になってしまうため、設定を指示した次第です。

2024-11-15 09:47 UTC, lenny817 commented
@naruto1031 @MasayaIkeno 
全て修正しました！
再レビューお願いします
https://github.com/unicorn-hal/unicorn-monorepo/pull/94/commits/0e45fa709281f9cecb028b0da9ea29529fde8ec3

2024-11-15 10:31 UTC, MasayaIkeno commented on api-server/src/main/kotlin/com/unicorn/api/domain/call/Call.kt
> +            callReservationID: CallReservationID,
@lenny817 @naruto1031 
ごめんここ間違えた

fun update 内の
callReservationID: CallReservationID,
ではなく、

fun create 内の
callReservationID: CallReservationID,
を削除してください。
(自動生成なのでユーザーから受け取らなくていいはず)

お手数おかけして申し訳ないです！

2024-11-15 10:35 UTC, MasayaIkeno commented on api-server/src/test/kotlin/com/unicorn/api/domain/call/CallTest.kt
fun update のテストもしてくれるとありがたいです！

2024-11-15 12:06 UTC, MasayaIkeno commented on api-server/src/test/kotlin/com/unicorn/api/domain/call/CallTest.kt
ドメイン層の update テストもお願いしたいです。

2024-11-16 03:18 UTC, MasayaIkeno commented on api-server/src/test/kotlin/com/unicorn/api/infrastructure/call/CallRepositoryTest.kt
> +        callRepository.store(call)
これだと更新テストではなく追加テストになってるかも

2024-11-16 03:31 UTC, naruto1031 commented on api-server/src/test/kotlin/com/unicorn/api/infrastructure/call/CallRepositoryTest.kt
> +        callRepository.store(call)
@lenny817 @lenny817 
createではなく、SQLを用いて保存してあるUUIDを用いて、fromStoreでTestされているとよいですね！！
```suggestion
    @Test
    fun `should update call reservation`() {
        val call =
            Call.fromStore(
                callReservationID = UUID.fromString('211177ed-92f8-a956-825f-c31b2cad8b15')
                doctorID = "12345",
                userID = "12345",
                callStartTime = OffsetDateTime.of(LocalDateTime.of(2021, 1, 1, 9, 0, 0), ZoneOffset.of("+09:00")),
                callEndTime = OffsetDateTime.of(LocalDateTime.of(2021, 1, 1, 9, 30, 0), ZoneOffset.of("+09:00")),
            )

        callRepository.store(call)
```

2024-11-16 10:53 UTC, MasayaIkeno reviewed
@lenny817 
実装は大丈夫そうです
テストの微修正だけお願いします！

2024-11-16 10:53 UTC, MasayaIkeno commented on api-server/src/test/resources/db/call/Insert_Parent_Doctor_Data.sql
> +    ('12345', 'b87ce0a0-3293-23ac-4afc-2983fc431957', 'Doctor', 'One', 'https://example.com/icon3', 'doctor3@example.com', NOW(), NOW(), NULL, '1234567892');
doctor_id に挿入する値を accounts テーブルに対応するよう、 '67890' に変更してください。

2024-11-16 10:53 UTC, MasayaIkeno commented on api-server/src/test/kotlin/com/unicorn/api/infrastructure/call/CallRepositoryTest.kt
> +            )
update 時に使用する値が SQL で INSERT してある値と一致してるっぽいので変更を加えてテストしましょう

例）callStartTime と callEndTime をそれぞれ 10:00 と 10:30 に変更する

2024-11-16 11:08 UTC, MasayaIkeno reviewed
コメントしました
対応お願いします！

2024-11-16 11:08 UTC, MasayaIkeno commented on api-server/src/main/resources/db/migration/V032__Refactor_CallReservations_Table.sql
すいません
別のプルリクで " V032 " を使用したため、このファイル名の " V032 "を " V033 " に変更してください
急な変更申し訳ないです！

2024-11-17 06:20 UTC, naruto1031 commented on api-server/src/test/resources/db/call/Insert_Parent_User_Data.sql
> +    ('12345', 'test', 'test', 'male', 'sample@test.com', '1990-01-01', 'test', '0000000', '00000000000', 'https://example.com', 170.4, 60.4, 'test', '2024-10-20 13:17:04.322379');
@lenny817 
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
ここはaccountsが変わったことで、user_idが`67890`に変更が必要に見えるのですが、どうでしょうか？

2024-11-17 06:24 UTC, lenny817 commented on api-server/src/test/resources/db/call/Insert_Parent_User_Data.sql
> +    ('12345', 'test', 'test', 'male', 'sample@test.com', '1990-01-01', 'test', '0000000', '00000000000', 'https://example.com', 170.4, 60.4, 'test', '2024-10-20 13:17:04.322379');
@naruto1031 
見落としていました、各所再修正してコミットします！

2024-11-17 06:32 UTC, naruto1031 approved these changes
個人的にはOKです。あとは
@MasayaIkeno 
のレビューを待ってください！

2024-11-17 06:32 UTC, naruto1031 commented on api-server/src/test/resources/db/call/Insert_Parent_Doctor_Data.sql
> +    ('12345', 'b87ce0a0-3293-23ac-4afc-2983fc431957', 'Doctor', 'One', 'https://example.com/icon3', 'doctor3@example.com', NOW(), NOW(), NULL, '1234567892');
doctorが12345, userが67890に変更になった

2024-11-17 09:50 UTC, merged